;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Sep 23 2026
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
.MODEL SMALL
.8086
.STACK 100H

.DATA

HOUR    DB 00
MINUTE  DB 00
SECOND  DB 00

FIELD   DB 00
SETMODE DB 00
LASTCLK DB 00

.CODE

START:

    MOV AX,@DATA
    MOV DS,AX

    ; 8255 control word
    ; PA = input
    ; PB = output
    ; PC = output
    MOV DX,0006H
    MOV AL,90H
    OUT DX,AL

MAIN:

    CALL DISPLAY
    CALL BUTTONS
    CALL CLOCK

    JMP MAIN


;========================================
; CLOCK
; PA0 = TIME_CLK
;========================================

CLOCK:

    MOV DX,0000H
    IN AL,DX

    AND AL,01H

    ; If setting time, don't count
    CMP SETMODE,01H
    JE CLOCK_SETTING

    ; Detect rising edge
    CMP AL,00H
    JE CLOCK_LOW

    CMP LASTCLK,00H
    JNE CLOCK_DONE

    ; Rising edge detected
    MOV LASTCLK,01H

    INC SECOND

    CMP SECOND,60
    JB CLOCK_DONE

    MOV SECOND,00
    INC MINUTE

    CMP MINUTE,60
    JB CLOCK_DONE

    MOV MINUTE,00
    INC HOUR

    CMP HOUR,24
    JB CLOCK_DONE

    MOV HOUR,00

CLOCK_DONE:
    RET


CLOCK_LOW:

    MOV LASTCLK,00H
    RET


CLOCK_SETTING:

    ; Reset edge detector while setting time
    MOV LASTCLK,00H
    RET


;========================================
; BUTTONS
;
; PA1 = SET/NEXT
; PA2 = UP
; PA3 = DOWN
;
; Buttons are active LOW
;========================================

BUTTONS:

    MOV DX,0000H
    IN AL,DX


;----------------------------------------
; SET BUTTON
;----------------------------------------

    TEST AL,02H
    JNZ CHECK_UP

    CALL DEBOUNCE

    IN AL,DX
    TEST AL,02H
    JNZ CHECK_UP

    CMP SETMODE,00H
    JNE NEXT_FIELD

    ; Enter setting mode
    MOV SETMODE,01H
    MOV FIELD,00H

    CALL WAIT_RELEASE
    RET


NEXT_FIELD:

    INC FIELD

    CMP FIELD,03
    JB SET_FINISH

    ; Finished seconds
    MOV FIELD,00H
    MOV SETMODE,00H

SET_FINISH:

    CALL WAIT_RELEASE
    RET


;----------------------------------------
; UP BUTTON
;----------------------------------------

CHECK_UP:

    TEST AL,04H
    JNZ CHECK_DOWN

    CMP SETMODE,01H
    JNE BUTTON_DONE

    CALL DEBOUNCE

    MOV DX,0000H
    IN AL,DX

    TEST AL,04H
    JNZ BUTTON_DONE

    CALL INCREASE

    CALL WAIT_RELEASE
    RET


;----------------------------------------
; DOWN BUTTON
;----------------------------------------

CHECK_DOWN:

    TEST AL,08H
    JNZ BUTTON_DONE

    CMP SETMODE,01H
    JNE BUTTON_DONE

    CALL DEBOUNCE

    MOV DX,0000H
    IN AL,DX

    TEST AL,08H
    JNZ BUTTON_DONE

    CALL DECREASE

    CALL WAIT_RELEASE
    RET


BUTTON_DONE:

    RET


;========================================
; INCREASE SELECTED FIELD
;========================================

INCREASE:

    CMP FIELD,00H
    JNE INC_MINUTE

    ; HOURS
    INC HOUR

    CMP HOUR,24
    JB INC_DONE

    MOV HOUR,00
    RET


INC_MINUTE:

    CMP FIELD,01H
    JNE INC_SECOND

    ; MINUTES
    INC MINUTE

    CMP MINUTE,60
    JB INC_DONE

    MOV MINUTE,00
    RET


INC_SECOND:

    ; SECONDS
    INC SECOND

    CMP SECOND,60
    JB INC_DONE

    MOV SECOND,00


INC_DONE:

    RET


;========================================
; DECREASE SELECTED FIELD
;========================================

DECREASE:

    CMP FIELD,00H
    JNE DEC_MINUTE

    ; HOURS
    CMP HOUR,00H
    JNE DEC_HOUR

    MOV HOUR,23
    RET


DEC_HOUR:

    DEC HOUR
    RET


DEC_MINUTE:

    CMP FIELD,01H
    JNE DEC_SECOND

    ; MINUTES
    CMP MINUTE,00H
    JNE DEC_MIN

    MOV MINUTE,59
    RET


DEC_MIN:

    DEC MINUTE
    RET


DEC_SECOND:

    ; SECONDS
    CMP SECOND,00H
    JNE DEC_SEC

    MOV SECOND,59
    RET


DEC_SEC:

    DEC SECOND
    RET


;========================================
; DISPLAY HH:MM:SS
;========================================

DISPLAY:


;----------------------------------------
; HOUR TENS
;----------------------------------------

    MOV AL,HOUR
    MOV AH,00H
    MOV BL,10
    DIV BL

    ; AL = tens
    CALL SEG7

    MOV AL,0FEH
    MOV DX,0004H
    OUT DX,AL

    CALL DELAY

    MOV AL,0FFH
    OUT DX,AL


;----------------------------------------
; HOUR UNITS
;----------------------------------------

    MOV AL,HOUR
    MOV AH,00H
    MOV BL,10
    DIV BL

    ; AH = remainder
    MOV AL,AH

    CALL SEG7

    MOV AL,0FDH
    MOV DX,0004H
    OUT DX,AL

    CALL DELAY

    MOV AL,0FFH
    OUT DX,AL


;----------------------------------------
; MINUTE TENS
;----------------------------------------

    MOV AL,MINUTE
    MOV AH,00H
    MOV BL,10
    DIV BL

    CALL SEG7

    MOV AL,0FBH
    MOV DX,0004H
    OUT DX,AL

    CALL DELAY

    MOV AL,0FFH
    OUT DX,AL


;----------------------------------------
; MINUTE UNITS
;----------------------------------------

    MOV AL,MINUTE
    MOV AH,00H
    MOV BL,10
    DIV BL

    MOV AL,AH

    CALL SEG7

    MOV AL,0F7H
    MOV DX,0004H
    OUT DX,AL

    CALL DELAY

    MOV AL,0FFH
    OUT DX,AL


;----------------------------------------
; SECOND TENS
;----------------------------------------

    MOV AL,SECOND
    MOV AH,00H
    MOV BL,10
    DIV BL

    CALL SEG7

    MOV AL,0EFH
    MOV DX,0004H
    OUT DX,AL

    CALL DELAY

    MOV AL,0FFH
    OUT DX,AL


;----------------------------------------
; SECOND UNITS
;----------------------------------------

    MOV AL,SECOND
    MOV AH,00H
    MOV BL,10
    DIV BL

    MOV AL,AH

    CALL SEG7

    MOV AL,0DFH
    MOV DX,0004H
    OUT DX,AL

    CALL DELAY

    MOV AL,0FFH
    OUT DX,AL

    RET


;========================================
; 7-SEGMENT CODE
;
; PB = 7-segment segments
;========================================

SEG7:

    CMP AL,00H
    JE DIGIT0

    CMP AL,01H
    JE DIGIT1

    CMP AL,02H
    JE DIGIT2

    CMP AL,03H
    JE DIGIT3

    CMP AL,04H
    JE DIGIT4

    CMP AL,05H
    JE DIGIT5

    CMP AL,06H
    JE DIGIT6

    CMP AL,07H
    JE DIGIT7

    CMP AL,08H
    JE DIGIT8

    ; 9
    MOV AL,6FH
    JMP SEG_OUT


DIGIT0:
    MOV AL,3FH
    JMP SEG_OUT

DIGIT1:
    MOV AL,06H
    JMP SEG_OUT

DIGIT2:
    MOV AL,5BH
    JMP SEG_OUT

DIGIT3:
    MOV AL,4FH
    JMP SEG_OUT

DIGIT4:
    MOV AL,66H
    JMP SEG_OUT

DIGIT5:
    MOV AL,6DH
    JMP SEG_OUT

DIGIT6:
    MOV AL,7DH
    JMP SEG_OUT

DIGIT7:
    MOV AL,07H
    JMP SEG_OUT

DIGIT8:
    MOV AL,7FH


SEG_OUT:

    MOV DX,0002H
    OUT DX,AL

    RET


;========================================
; BUTTON DEBOUNCE
;========================================

DEBOUNCE:

    MOV CX,1000

DB_LOOP:

    LOOP DB_LOOP

    RET


;========================================
; WAIT FOR BUTTON RELEASE
;========================================

WAIT_RELEASE:

RELEASE_LOOP:

    MOV DX,0000H
    IN AL,DX

    AND AL,0EH

    CMP AL,0EH
    JNE RELEASE_LOOP

    RET


;========================================
; DISPLAY DELAY
;========================================

DELAY:

    MOV CX,100

DELAY_LOOP:

    LOOP DELAY_LOOP

    RET


END START